name: Features
state: {}
props:
  - features
ui:
  tag: div
  class: overflow-hidden bg-white py-24 sm:py-32
  children:
    - tag: div
      class: mx-auto max-w-7xl px-6 lg:px-8
      children:
        - tag: div
          class: >-
            mx-auto grid max-w-2xl grid-cols-1 gap-y-16 gap-x-8 sm:gap-y-20
            lg:mx-0 lg:max-w-none lg:grid-cols-2
          children:
            - tag: div
              class: lg:pr-8 lg:pt-4
              children:
                - tag: div
                  class: lg:max-w-lg
                  children:
                    - tag: h2
                      class: >-
                        text-lg font-semibold leading-8 tracking-tight
                        text-indigo-600
                      children:
                        - Deploy faster
                    - tag: p
                      class: >-
                        mt-2 text-3xl font-foundation tracking-tight text-gray-900
                        sm:text-4xl
                      children:
                        - A better workflow
                    - tag: p
                      class: mt-6 text-lg leading-8 text-gray-600
                      children:
                        - >-
                          Lorem ipsum, dolor sit amet consectetur adipisicing
                          elit. Maiores impedit perferendis suscipit eaque, iste
                          dolor cupiditate blanditiis ratione.
                    - tag: dl
                      class: >-
                        mt-10 max-w-xl space-y-8 text-base leading-7
                        text-gray-600 lg:max-w-none
                      children:
                        - '{features.map((feature) => ('
                        - tag: div
                          key: '{feature.key}'
                          class: relative pl-9
                          children:
                            - tag: dt
                              class: inline font-semibold text-gray-900
                              children:
                                - tag: feature.icon
                                  aria-hidden: 'true'
                                  class: >-
                                    absolute top-1 left-1 h-5 w-5
                                    text-indigo-600
                                - '{feature.title}'
                            - "{' '}"
                            - tag: dd
                              class: inline
                              children:
                                - '{feature.description}'
                        - ))}
            - tag: img
              src: >-
                https://tailwindui.com/img/component-images/dark-project-app-screenshot.png
              alt: Product screenshot
              width: '{2432}'
              height: '{1442}'
              class: >-
                w-[48rem] max-w-none rounded-xl shadow-xl ring-1
                ring-gray-400/10 sm:w-[57rem] md:-ml-4 lg:-ml-0
