name: Footer
state: {}
props:
  - navigation
ui:
  tag: footer
  class: bg-white
  children:
    - tag: div
      class: mx-auto max-w-7xl overflow-hidden py-20 px-6 sm:py-24 lg:px-8
      children:
        - tag: nav
          aria-label: Footer
          class: '-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12'
          children:
            - '{navigation.map((item) => ('
            - tag: div
              key: '{item.key}'
              class: pb-6
              children:
                - tag: a
                  href: '{item.path}'
                  class: text-sm leading-6 text-gray-600 hover:text-gray-900
                  children:
                    - '{t(`header.navigation.${item.key}`)}'
            - ))}
        - tag: p
          class: mt-10 text-center text-xs leading-5 text-gray-500
          children:
            - '{t("footer.copyright")}'
