name: Header
state: {}
props:
  - navigation
  - logo
  - buttons
ui:
  tag: Popover
  class: relative bg-white
  children:
    - tag: div
      class: flex items-center justify-between p-6 md:justify-start md:space-x-10
      children:
        - tag: div
          class: flex justify-start lg:w-0 lg:flex-1
          children:
            - tag: a
              href: '/'
              children:
                - tag: span
                  class: sr-only
                  children:
                    - '{t("header.logoTitle")}'
                - tag: img
                  src: '{logo.path}'
                  alt: '{t("header.logoTitle")}'
                  class: h-8 w-auto sm:h-10
                  width: '{logo.width}'
                  height: '{logo.height}'
        - tag: div
          class: '-my-2 -mr-2 md:hidden'
          children:
            - tag: Popover.Button
              class: >-
                inline-flex items-center justify-center rounded-md bg-white p-2
                text-gray-400 hover:bg-gray-100 hover:text-gray-500
                focus:outline-none focus:ring-2 focus:ring-inset
                focus:ring-primary-500
              children:
                - tag: span
                  class: sr-only
                  children:
                    - '{t("header.mobileMenu")}'
                - tag: Bars3Icon
                  aria-hidden: 'true'
                  class: h-6 w-6
        - tag: Popover.Group
          as: nav
          class: hidden space-x-10 md:flex
          children:
            - '{navigation.map((item) => ('
            - tag: a
              href: '{item.path}'
              key: '{item.key}'
              class: text-base font-medium text-gray-500 hover:text-gray-900
              children:
                - '{item.key}'
            - '))}'
        - tag: div
          class: hidden items-center justify-end md:flex md:flex-1 lg:w-0
          children:
            - tag: a
              href: '{buttons.primary.path}'
              class: >-
                ml-8 inline-flex items-center justify-center whitespace-nowrap
                rounded-md border border-transparent bg-primary-600 px-4 py-2
                text-base font-medium text-white shadow-sm hover:bg-primary-700
              children:
                - Sign up