name: Header
state: {}
props:
  - solutions
  - resources
  - classNames
ui:
  tag: Popover
  class: relative bg-white
  children:
    - tag: div
      class: flex items-center justify-between p-6 md:justify-start md:space-x-10
      children:
        - tag: div
          class: flex justify-start lg:w-0 lg:flex-1
          children:
            - tag: a
              href: '#'
              children:
                - tag: span
                  class: sr-only
                  children:
                    - Your Company
                - tag: img
                  src: >-
                    https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600
                  alt: ''
                  class: h-8 w-auto sm:h-10
        - tag: div
          class: '-my-2 -mr-2 md:hidden'
          children:
            - tag: Popover.Button
              class: >-
                inline-flex items-center justify-center rounded-md bg-white p-2
                text-gray-400 hover:bg-gray-100 hover:text-gray-500
                focus:outline-none focus:ring-2 focus:ring-inset
                focus:ring-indigo-500
              children:
                - tag: span
                  class: sr-only
                  children:
                    - Open menu
                - tag: Bars3Icon
                  aria-hidden: 'true'
                  class: h-6 w-6
        - tag: Popover.Group
          as: nav
          class: hidden space-x-10 md:flex
          children:
            - tag: Popover
              class: relative
              children:
                - '{({ open }) => ('
                - tag: ''
                  children:
                    - tag: Popover.Button
                      class: >-
                        {classNames(                    open ? 'text-gray-900' :
                        'text-gray-500',                    'group inline-flex
                        items-center rounded-md bg-white text-base font-medium
                        hover:text-gray-900 focus:outline-none focus:ring-2
                        focus:ring-indigo-500
                        focus:ring-offset-2'                  )}
                      children:
                        - tag: span
                          children:
                            - Solutions
                        - tag: ChevronDownIcon
                          aria-hidden: 'true'
                          class: >-
                            {classNames(                      open ?
                            'text-gray-600' :
                            'text-gray-400',                      'ml-2 h-5 w-5
                            group-hover:text-gray-500'                    )}
                    - tag: Transition
                      as: '{Fragment}'
                      enter: transition ease-out duration-200
                      enterFrom: opacity-0 translate-y-1
                      enterTo: opacity-100 translate-y-0
                      leave: transition ease-in duration-150
                      leaveFrom: opacity-100 translate-y-0
                      leaveTo: opacity-0 translate-y-1
                      children:
                        - tag: Popover.Panel
                          class: >-
                            absolute z-10 -ml-4 mt-3 w-screen max-w-md transform
                            lg:left-1/2 lg:ml-0 lg:max-w-2xl lg:-translate-x-1/2
                          children:
                            - tag: div
                              class: >-
                                overflow-hidden rounded-lg shadow-lg ring-1
                                ring-black ring-opacity-5
                              children:
                                - tag: div
                                  class: >-
                                    relative grid gap-6 bg-white px-5 py-6
                                    sm:gap-8 sm:p-8 lg:grid-cols-2
                                  children:
                                    - '{solutions.map((solution) => ('
                                    - tag: a
                                      key: '{solution.name}'
                                      href: '{solution.href}'
                                      class: >-
                                        -m-3 flex items-start rounded-lg p-3
                                        hover:bg-gray-50
                                      children:
                                        - tag: div
                                          class: >-
                                            flex h-10 w-10 flex-shrink-0
                                            items-center justify-center rounded-md
                                            bg-indigo-500 text-white sm:h-12 sm:w-12
                                          children:
                                            - tag: solution.icon
                                              aria-hidden: 'true'
                                              class: h-6 w-6
                                        - tag: div
                                          class: ml-4
                                          children:
                                            - tag: p
                                              class: text-base font-medium text-gray-900
                                              children:
                                                - '{solution.name}'
                                            - tag: p
                                              class: mt-1 text-sm text-gray-500
                                              children:
                                                - '{solution.description}'
                                    - ))}
                                - tag: div
                                  class: bg-gray-50 p-5 sm:p-8
                                  children:
                                    - tag: a
                                      href: '#'
                                      class: >-
                                        -m-3 flow-root rounded-md p-3
                                        hover:bg-gray-100
                                      children:
                                        - tag: div
                                          class: flex items-center
                                          children:
                                            - tag: div
                                              class: text-base font-medium text-gray-900
                                              children:
                                                - Enterprise
                                            - tag: span
                                              class: >-
                                                ml-3 inline-flex items-center
                                                rounded-full bg-indigo-100 px-3 py-0.5
                                                text-xs font-medium leading-5
                                                text-indigo-800
                                              children:
                                                - New
                                        - tag: p
                                          class: mt-1 text-sm text-gray-500
                                          children:
                                            - >-
                                              Empower your entire team with even more
                                              advanced tools.
                - )}
            - tag: a
              href: '#'
              class: text-base font-medium text-gray-500 hover:text-gray-900
              children:
                - Pricing
            - tag: a
              href: '#'
              class: text-base font-medium text-gray-500 hover:text-gray-900
              children:
                - Docs
            - tag: Popover
              class: relative
              children:
                - '{({ open }) => ('
                - tag: ''
                  children:
                    - tag: Popover.Button
                      class: >-
                        {classNames(                    open ? 'text-gray-900' :
                        'text-gray-500',                    'group inline-flex
                        items-center rounded-md bg-white text-base font-medium
                        hover:text-gray-900 focus:outline-none focus:ring-2
                        focus:ring-indigo-500
                        focus:ring-offset-2'                  )}
                      children:
                        - tag: span
                          children:
                            - More
                        - tag: ChevronDownIcon
                          aria-hidden: 'true'
                          class: >-
                            {classNames(                      open ?
                            'text-gray-600' :
                            'text-gray-400',                      'ml-2 h-5 w-5
                            group-hover:text-gray-500'                    )}
                    - tag: Transition
                      as: '{Fragment}'
                      enter: transition ease-out duration-200
                      enterFrom: opacity-0 translate-y-1
                      enterTo: opacity-100 translate-y-0
                      leave: transition ease-in duration-150
                      leaveFrom: opacity-100 translate-y-0
                      leaveTo: opacity-0 translate-y-1
                      children:
                        - tag: Popover.Panel
                          class: >-
                            absolute left-1/2 z-10 mt-3 w-screen max-w-xs
                            -translate-x-1/2 transform px-2 sm:px-0
                          children:
                            - tag: div
                              class: >-
                                overflow-hidden rounded-lg shadow-lg ring-1
                                ring-black ring-opacity-5
                              children:
                                - tag: div
                                  class: >-
                                    relative grid gap-6 bg-white px-5 py-6
                                    sm:gap-8 sm:p-8
                                  children:
                                    - '{resources.map((resource) => ('
                                    - tag: a
                                      key: '{resource.name}'
                                      href: '{resource.href}'
                                      class: >-
                                        -m-3 block rounded-md p-3
                                        hover:bg-gray-50
                                      children:
                                        - tag: p
                                          class: text-base font-medium text-gray-900
                                          children:
                                            - '{resource.name}'
                                        - tag: p
                                          class: mt-1 text-sm text-gray-500
                                          children:
                                            - '{resource.description}'
                                    - ))}
                - )}
        - tag: div
          class: hidden items-center justify-end md:flex md:flex-1 lg:w-0
          children:
            - tag: a
              href: '#'
              class: >-
                whitespace-nowrap text-base font-medium text-gray-500
                hover:text-gray-900
              children:
                - Sign in
            - tag: a
              href: '#'
              class: >-
                ml-8 inline-flex items-center justify-center whitespace-nowrap
                rounded-md border border-transparent bg-indigo-600 px-4 py-2
                text-base font-medium text-white shadow-sm hover:bg-indigo-700
              children:
                - Sign up
    - tag: Transition
      as: '{Fragment}'
      enter: duration-200 ease-out
      enterFrom: opacity-0 scale-95
      enterTo: opacity-100 scale-100
      leave: duration-100 ease-in
      leaveFrom: opacity-100 scale-100
      leaveTo: opacity-0 scale-95
      children:
        - tag: Popover.Panel
          focus: 'true'
          class: >-
            absolute inset-x-0 top-0 origin-top-right transform p-2 transition
            md:hidden
          children:
            - tag: div
              class: >-
                divide-y-2 divide-gray-50 rounded-lg bg-white shadow-lg ring-1
                ring-black ring-opacity-5
              children:
                - tag: div
                  class: px-5 pt-5 pb-6
                  children:
                    - tag: div
                      class: flex items-center justify-between
                      children:
                        - tag: div
                          children:
                            - tag: img
                              src: >-
                                https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600
                              alt: Your Company
                              class: h-8 w-auto
                        - tag: div
                          class: '-mr-2'
                          children:
                            - tag: Popover.Button
                              class: >-
                                inline-flex items-center justify-center
                                rounded-md bg-white p-2 text-gray-400
                                hover:bg-gray-100 hover:text-gray-500
                                focus:outline-none focus:ring-2 focus:ring-inset
                                focus:ring-indigo-500
                              children:
                                - tag: span
                                  class: sr-only
                                  children:
                                    - Close menu
                                - tag: XMarkIcon
                                  aria-hidden: 'true'
                                  class: h-6 w-6
                    - tag: div
                      class: mt-6
                      children:
                        - tag: nav
                          class: grid grid-cols-1 gap-7
                          children:
                            - '{solutions.map((solution) => ('
                            - tag: a
                              key: '{solution.name}'
                              href: '{solution.href}'
                              class: >-
                                -m-3 flex items-center rounded-lg p-3
                                hover:bg-gray-50
                              children:
                                - tag: div
                                  class: >-
                                    flex h-10 w-10 flex-shrink-0 items-center
                                    justify-center rounded-md bg-indigo-500
                                    text-white
                                  children:
                                    - tag: solution.icon
                                      aria-hidden: 'true'
                                      class: h-6 w-6
                                - tag: div
                                  class: ml-4 text-base font-medium text-gray-900
                                  children:
                                    - '{solution.name}'
                            - ))}
                - tag: div
                  class: py-6 px-5
                  children:
                    - tag: div
                      class: grid grid-cols-2 gap-4
                      children:
                        - tag: a
                          href: '#'
                          class: >-
                            text-base font-medium text-gray-900
                            hover:text-gray-700
                          children:
                            - Pricing
                        - tag: a
                          href: '#'
                          class: >-
                            text-base font-medium text-gray-900
                            hover:text-gray-700
                          children:
                            - Docs
                        - tag: a
                          href: '#'
                          class: >-
                            text-base font-medium text-gray-900
                            hover:text-gray-700
                          children:
                            - Enterprise
                        - '{resources.map((resource) => ('
                        - tag: a
                          key: '{resource.name}'
                          href: '{resource.href}'
                          class: >-
                            text-base font-medium text-gray-900
                            hover:text-gray-700
                          children:
                            - '{resource.name}'
                        - ))}
                    - tag: div
                      class: mt-6
                      children:
                        - tag: a
                          href: '#'
                          class: >-
                            flex w-full items-center justify-center rounded-md
                            border border-transparent bg-indigo-600 px-4 py-2
                            text-base font-medium text-white shadow-sm
                            hover:bg-indigo-700
                          children:
                            - Sign up
                        - tag: p
                          class: mt-6 text-center text-base font-medium text-gray-500
                          children:
                            - Existing customer?{' '}
                            - tag: a
                              href: '#'
                              class: text-indigo-600 hover:text-indigo-500
                              children:
                                - Sign in
