name: Hero
state: {}
props: []
ui:
  tag: div
  class: relative isolate overflow-hidden bg-white
  children:
    - tag: svg
      aria-hidden: 'true'
      class: >-
        absolute inset-0 -z-10 h-full w-full stroke-gray-200
        [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]
      children:
        - tag: defs
          children:
            - tag: pattern
              id: 0787a7c5-978c-4f66-83c7-11c213f99cb7
              width: '{200}'
              height: '{200}'
              x: 50%
              y: '{-1}'
              patternUnits: userSpaceOnUse
              children:
                - tag: path
                  d: M.5 200V.5H200
                  fill: none
        - tag: rect
          width: 100%
          height: 100%
          strokeWidth: '{0}'
          fill: url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)
    - tag: div
      class: mx-auto max-w-7xl px-6 pt-10 pb-24 sm:pb-32 lg:flex lg:py-40 lg:px-8
      children:
        - tag: div
          class: mx-auto max-w-2xl lg:mx-0 lg:max-w-xl lg:flex-shrink-0 lg:pt-8
          children:
            - tag: img
              src: https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600
              alt: Your Company
              class: h-11
            - tag: div
              class: mt-24 sm:mt-32 lg:mt-16
              children:
                - tag: a
                  href: '#'
                  class: inline-flex space-x-6
                  children:
                    - tag: span
                      class: >-
                        rounded-full bg-indigo-600/10 px-3 py-1 text-sm
                        font-semibold leading-6 text-indigo-600 ring-1
                        ring-inset ring-indigo-600/10
                      children:
                        - What&apos;s new
                    - tag: span
                      class: >-
                        inline-flex items-center space-x-2 text-sm font-medium
                        leading-6 text-gray-600
                      children:
                        - tag: span
                          children:
                            - Just shipped v1.0
                        - tag: ChevronRightIcon
                          aria-hidden: 'true'
                          class: h-5 w-5 text-gray-400
            - tag: h1
              class: >-
                mt-10 text-4xl font-bold tracking-tight text-gray-900
                sm:text-6xl
              children:
                - '{t("hero.title")}'
            - tag: p
              class: mt-6 text-lg leading-8 text-gray-600
              children:
                - >-
                  Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure
                  qui lorem cupidatat commodo. Elit sunt amet fugiat veniam
                  occaecat fugiat aliqua.
            - tag: div
              class: mt-10 flex items-center gap-x-6
              children:
                - tag: a
                  href: '#'
                  class: >-
                    rounded-md bg-indigo-600 px-3.5 py-1.5 text-base
                    font-semibold leading-7 text-white shadow-sm
                    hover:bg-indigo-500 focus-visible:outline
                    focus-visible:outline-2 focus-visible:outline-offset-2
                    focus-visible:outline-indigo-600
                  children:
                    - Get started
                - tag: a
                  href: '#'
                  class: text-base font-semibold leading-7 text-gray-900
                  children:
                    - Learn more
                    - tag: span
                      aria-hidden: 'true'
                      children:
                        - →
        - tag: div
          class: >-
            mx-auto mt-16 flex max-w-2xl sm:mt-24 lg:ml-10 lg:mt-0 lg:mr-0
            lg:max-w-none lg:flex-none xl:ml-32
          children:
            - tag: div
              class: max-w-3xl flex-none sm:max-w-5xl lg:max-w-none
              children:
                - tag: div
                  class: >-
                    -m-2 rounded-xl bg-gray-900/5 p-2 ring-1 ring-inset
                    ring-gray-900/10 lg:-m-4 lg:rounded-2xl lg:p-4
                  children:
                    - tag: img
                      src: >-
                        https://tailwindui.com/img/component-images/project-app-screenshot.png
                      alt: App screenshot
                      width: '{2432}'
                      height: '{1442}'
                      class: w-[76rem] rounded-md shadow-2xl ring-1 ring-gray-900/10
