name: Footer
state: {}
props:
  - navigation
ui:
  tag: footer
  class: bg-white
  children:
    - tag: div
      class: mx-auto max-w-7xl overflow-hidden py-20 px-6 sm:py-24 lg:px-8
      children:
        - tag: nav
          aria-label: Footer
          class: '-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12'
          children:
            - '{navigation.main.map((item) => ('
            - tag: div
              key: '{item.name}'
              class: pb-6
              children:
                - tag: a
                  href: '{item.href}'
                  class: text-sm leading-6 text-gray-600 hover:text-gray-900
                  children:
                    - '{item.name}'
            - ))}
        - tag: div
          class: mt-10 flex justify-center space-x-10
          children:
            - '{navigation.social.map((item) => ('
            - tag: a
              key: '{item.name}'
              href: '{item.href}'
              class: text-gray-400 hover:text-gray-500
              children:
                - tag: span
                  class: sr-only
                  children:
                    - '{item.name}'
                - tag: item.icon
                  aria-hidden: 'true'
                  class: h-6 w-6
            - ))}
        - tag: p
          class: mt-10 text-center text-xs leading-5 text-gray-500
          children:
            - '&copy; 2020 Your Company, Inc. All rights reserved.'
