name: Stats
state: {}
props: []
ui:
  tag: div
  class: bg-gray-50 pt-12 sm:pt-16
  children:
    - tag: div
      class: mx-auto max-w-7xl px-6 lg:px-8
      children:
        - tag: div
          class: mx-auto max-w-4xl text-center
          children:
            - tag: h2
              class: text-3xl font-foundation tracking-tight text-gray-900 sm:text-4xl
              children:
                - Trusted by developers from over 80 planets
            - tag: p
              class: mt-3 text-xl text-gray-500 sm:mt-4
              children:
                - >-
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                  Repellendus repellat laudantium.
    - tag: div
      class: mt-10 bg-white pb-12 sm:pb-16
      children:
        - tag: div
          class: relative
          children:
            - tag: div
              class: absolute inset-0 h-1/2 bg-gray-50
            - tag: div
              class: relative mx-auto max-w-7xl px-6 lg:px-8
              children:
                - tag: div
                  class: mx-auto max-w-4xl
                  children:
                    - tag: dl
                      class: rounded-lg bg-white shadow-lg sm:grid sm:grid-cols-3
                      children:
                        - tag: div
                          class: >-
                            flex flex-col border-b border-gray-100 p-6
                            text-center sm:border-0 sm:border-r
                          children:
                            - tag: dt
                              class: >-
                                order-2 mt-2 text-lg font-medium leading-6
                                text-gray-500
                              children:
                                - Pepperoni
                            - tag: dd
                              class: >-
                                order-1 text-5xl font-foundation tracking-tight
                                text-indigo-600
                              children:
                                - 100%
                        - tag: div
                          class: >-
                            flex flex-col border-t border-b border-gray-100 p-6
                            text-center sm:border-0 sm:border-l sm:border-r
                          children:
                            - tag: dt
                              class: >-
                                order-2 mt-2 text-lg font-medium leading-6
                                text-gray-500
                              children:
                                - Delivery
                            - tag: dd
                              class: >-
                                order-1 text-5xl font-foundation tracking-tight
                                text-indigo-600
                              children:
                                - 24/7
                        - tag: div
                          class: >-
                            flex flex-col border-t border-gray-100 p-6
                            text-center sm:border-0 sm:border-l
                          children:
                            - tag: dt
                              class: >-
                                order-2 mt-2 text-lg font-medium leading-6
                                text-gray-500
                              children:
                                - Calories
                            - tag: dd
                              class: >-
                                order-1 text-5xl font-foundation tracking-tight
                                text-indigo-600
                              children:
                                - 100k
