name: Testimonials
state: {}
props: []
ui:
  tag: section
  class: overflow-hidden bg-gray-50 py-12 md:py-20 lg:py-24
  children:
    - tag: div
      class: relative mx-auto max-w-7xl px-6 lg:px-8
      children:
        - tag: svg
          width: '{404}'
          height: '{404}'
          fill: none
          viewBox: 0 0 404 404
          role: img
          aria-labelledby: svg-workcation
          class: >-
            absolute top-full right-full translate-x-1/3 -translate-y-1/4
            transform lg:translate-x-1/2 xl:-translate-y-1/2
          children:
            - tag: title
              id: svg-workcation
              children:
                - Workcation
            - tag: defs
              children:
                - tag: pattern
                  id: ad119f34-7694-4c31-947f-5c9d249b21f3
                  x: '{0}'
                  'y': '{0}'
                  width: '{20}'
                  height: '{20}'
                  patternUnits: userSpaceOnUse
                  children:
                    - tag: rect
                      x: '{0}'
                      'y': '{0}'
                      width: '{4}'
                      height: '{4}'
                      fill: currentColor
                      class: text-gray-200
            - tag: rect
              width: '{404}'
              height: '{404}'
              fill: url(#ad119f34-7694-4c31-947f-5c9d249b21f3)
        - tag: div
          class: relative
          children:
            - tag: img
              src: >-
                https://tailwindui.com/img/logos/workcation-logo-indigo-600-mark-gray-800-and-indigo-600-text.svg
              alt: Workcation
              class: mx-auto h-8
              width: '50'
              height: '50'
            - tag: blockquote
              class: mt-10
              children:
                - tag: div
                  class: >-
                    mx-auto max-w-3xl text-center text-2xl font-medium leading-9
                    text-gray-900
                  children:
                    - tag: p
                      children:
                        - >-
                          &ldquo;Lorem ipsum dolor sit amet consectetur
                          adipisicing elit. Nemo expedita voluptas culpa
                          sapiente alias molestiae. Numquam corrupti in laborum
                          sed rerum et corporis.&rdquo;
                - tag: footer
                  class: mt-8
                  children:
                    - tag: div
                      class: md:flex md:items-center md:justify-center
                      children:
                        - tag: div
                          class: md:flex-shrink-0
                          children:
                            - tag: img
                              src: >-
                                https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80
                              alt: ''
                              class: mx-auto h-10 w-10 rounded-full
                              width: '50'
                              height: '50'
                        - tag: div
                          class: >-
                            mt-3 text-center md:mt-0 md:ml-4 md:flex
                            md:items-center
                          children:
                            - tag: div
                              class: text-base font-medium text-gray-900
                              children:
                                - Judith Black
                            - tag: svg
                              fill: currentColor
                              viewBox: 0 0 20 20
                              class: mx-1 hidden h-5 w-5 text-indigo-600 md:block
                              children:
                                - tag: path
                                  d: M11 0h3L9 20H6l5-20z
                            - tag: div
                              class: text-base font-medium text-gray-500
                              children:
                                - CEO, Workcation
