version: '3.9'

networks:
  e2e-network:
    driver: bridge

services:
  db:
    image: postgres:13
    restart: always
    container_name: e2e-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    networks:
      - e2e-network