version: '3.9'

networks:
  invoices-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: invoices-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - invoices-network