# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bun CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [1.x]

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run lint
    - run: bun run build --if-present
    - run: bunx playwright install
    - run: bunx @puppeteer/browsers install chrome@stable --path $HOME/.cache/puppeteer
    - run: bun run test
    #- name: Release
      #env:
        #GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #run: bunx semantic-release
    
