name: Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Run Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      TEST_SENTRY_AUTH_TOKEN: ${{ secrets.TEST_SENTRY_AUTH_TOKEN }}
      TEST_SENTRY_ORGANIZATION: ${{ secrets.TEST_SENTRY_ORGANIZATION }}
      TEST_SENTRY_PROJECT: ${{ secrets.TEST_SENTRY_PROJECT }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      TEST_ELASTICSEARCH_URL: ${{ secrets.TEST_ELASTICSEARCH_URL }}
      TEST_ELASTICSEARCH_INDEX: ${{ secrets.TEST_ELASTICSEARCH_INDEX }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: sudo sysctl -w kernel.unprivileged_userns_clone=1
      - run: bun install
      - run: bun run lint
      - run: bun run build
      - run: bun run test

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bunx semantic-release
